# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#
domain: "abdorithm.github.io"      # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: "https://abdorithm.github.io"  # the base hostname and protocol for your site, e.g. http://example.com

title: abdorithm's blog
email: abdomagdi300@gmail.com 
description: >- # this means to ignore newlines until "baseurl:"
  This is my mind arena. I write about whatever I tinkered with recently. 
  I used to write stuff as notes in my Obsidian. Now I intend to migrate here.
  FOSS, Linux, Security, Privacy, and Gaming (on linux ^-^), in no particular order.
twitter_username: Abdorithm
github_username:  Abdorithm

# Build settings
remote_theme: jekyll/minima@v2.5.1
minima:
  skin: dark

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
